# Generated by Django 5.0.6 on 2024-07-15 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_middleagedata_oldagedata_youngagedata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='femalepopulationdata',
            table='female_population_data',
        ),
        migrations.AlterModelTable(
            name='malepopulationdata',
            table='male_population_data',
        ),
        migrations.AlterModelTable(
            name='middleagedata',
            table='middle_age_data',
        ),
        migrations.AlterModelTable(
            name='oldagedata',
            table='old_age_data',
        ),
        migrations.AlterModelTable(
            name='totalpopulationdata',
            table='total_population_data',
        ),
        migrations.AlterModelTable(
            name='youngagedata',
            table='young_age_data',
        ),
    ]
